name: ThunderPvPractice
version: ${project.version}
main: com.thunderpvp.thunderpvppractice.ThunderPvPractice
author: Jules
description: A practice plugin for PvP.
commands:
  thunderpvp:
    description: Main command for ThunderPvPractice.
    usage: /<command> [subcommand]
