name: ThunderPvPractice
version: ${project.version}
main: com.thunderpvp.thunderpvppractice.ThunderPvPractice
description: A practice plugin for PvP.
commands:
  thunderpvp:
    description: Main command for ThunderPvPractice.
    usage: /<command> [subcommand]
  duel:
    description: Challenge a player to a duel.
    usage: /<command> <player> <kit>
  accept:
    description: Accept a duel request.
    usage: /<command> [player]
  deny:
    description: Deny a duel request.
    usage: /<command> [player]
